"""
clusterHeatMap.py
=================

Sandbox / scratch script used while developing the clustered-heatmap layout
that is used in production by ``mappingstest.py``.

The script first draws a default ``sns.clustermap`` over the seaborn
``iris`` demo dataset to verify the styling, then re-draws the same
dataframe using the publication-style layout parameters (column-only
clustering, ``mako`` colormap, no row dendrogram, slim colorbar in the
upper-left).

Treat this file as a layout playground - the canonical KG figures are
generated by ``mappingstest.py``.

Reference
---------
Cortes et al., "Improving Biomedical Knowledge Graph Quality: A Community
Approach," arXiv:2508.21774 (2025).
"""

import seaborn as sns
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import set_link_color_palette
import pandas as pd

# Load an example dataset from seaborn
iris = sns.load_dataset("iris")
# Remove the 'species' column to leave only numerical data for clustering
df_numeric = iris.pop("species")
# Load the full dataset again for the numeric values
df = sns.load_dataset("iris").drop("species", axis=1)

# Create the clustered heatmap
# The function automatically performs hierarchical clustering
sns.clustermap(df)

# Display the plot
plt.show()

# When applied to the real KG figure the dataframe shape is:
#   df: rows = edge types, columns = knowledge graphs
#   index = edge types, columns = KG names

# Force dendrogram colors
#set_link_colr_palette(["green", "blue"])

# Publication-style layout: cluster only the columns (KGs), keep rows in
# their input order, and use a tight slim colorbar in the upper-left
# corner.
g = sns.clustermap(
    df,
    cmap="mako",
    row_cluster=False,      # 🚫 no left dendrogram
    col_cluster=True,       # ✅ top dendrogram
    dendrogram_ratio=(.15, .05),
    cbar_pos=(.02, .8, .03, .18),
    linewidths=0,
    figsize=(10, 6),
    tree_kws=dict(linewidths=1.5)
)

# Axis labels
g.ax_heatmap.set_xlabel("Knowledge Graph")
g.ax_heatmap.set_ylabel("Edge Type")

# Rotate KG labels if needed
plt.setp(g.ax_heatmap.get_xticklabels(), rotation=45, ha="right")

plt.show()
